name: SimCube BuildTool
description: Executes the SimCube Build Tool.

inputs:
  setupDotNet:
    description: Boolean flag which declares if dotnet should be setup.
    required: false
    default: 'false'
  checkout:
    description: Boolean flag which declares if git checkout should take place or not by this script.
    required: false
    default: 'false'
  installRequired:
    description: Boolean flag which declares if should install required tools.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
   
    - if: ${{ inputs.checkout == 'true' }} 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - if: ${{ inputs.setupDotNet == 'true' }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
        
    - if: ${{ inputs.installRequired == 'true' }}
      shell: bash
      run: |
        dotnet tool update -g SimCube.BuildTool
        dotnet tool update -g dotnet-sonarscanner
        
    - run: echo "::add-matcher::${GITHUB_ACTION_PATH}/matcher.json"
      shell: bash
      
    - name: Run Script
      run: ${GITHUB_ACTION_PATH}/script.sh
      shell: bash
      
    - run: echo "::remove-matcher owner=bash-action::"
      shell: bash
